name = "TradingAgents"
uuid = "a932613d-76ea-43ff-97dc-a74afa0c30e6"
authors = ["aaron-wheeler"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
